name = "Twizzy Craft 3"
author = "TTwistz22"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0af912ba3117acbdbf250326cc158f35d3e69bdf83d8d3c019661e8900e360f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
