name = "Twizzy Craft 3"
author = "KindaQuackDev"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "92816006d07b62feef6541c54b4e8a40a8af48c83b15fdc5dcf134c0970e7e07"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
