name = "Twizzy Craft 3"
author = "TTwistz22"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73ff236a169b1905b958b164bed3016279b85c6cea700c4b4a9ef0a55d4e5b0b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
